# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GoogleTest_config = debug
  SDL3_config = debug
  ImGui_config = debug
  Library_config = debug
  Application_config = debug
  Test_config = debug

else ifeq ($(config),release)
  GoogleTest_config = release
  SDL3_config = release
  ImGui_config = release
  Library_config = release
  Application_config = release
  Test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GoogleTest SDL3 ImGui Library Application Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GoogleTest:
ifneq (,$(GoogleTest_config))
	@echo "==== Building GoogleTest ($(GoogleTest_config)) ===="
	@${MAKE} --no-print-directory -C Generated/Projects -f GoogleTest.make config=$(GoogleTest_config)
endif

SDL3:
ifneq (,$(SDL3_config))
	@echo "==== Building SDL3 ($(SDL3_config)) ===="
	@${MAKE} --no-print-directory -C . -f SDL3.make config=$(SDL3_config)
endif

ImGui: SDL3
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C . -f ImGui.make config=$(ImGui_config)
endif

Library:
ifneq (,$(Library_config))
	@echo "==== Building Library ($(Library_config)) ===="
	@${MAKE} --no-print-directory -C Library -f Makefile config=$(Library_config)
endif

Application: Library ImGui SDL3
ifneq (,$(Application_config))
	@echo "==== Building Application ($(Application_config)) ===="
	@${MAKE} --no-print-directory -C Application -f Makefile config=$(Application_config)
endif

Test: Library GoogleTest
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C Generated/Projects -f Test.make config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C Generated/Projects -f GoogleTest.make clean
	@${MAKE} --no-print-directory -C . -f SDL3.make clean
	@${MAKE} --no-print-directory -C . -f ImGui.make clean
	@${MAKE} --no-print-directory -C Library -f Makefile clean
	@${MAKE} --no-print-directory -C Application -f Makefile clean
	@${MAKE} --no-print-directory -C Generated/Projects -f Test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GoogleTest"
	@echo "   SDL3"
	@echo "   ImGui"
	@echo "   Library"
	@echo "   Application"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"