# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
TARGETDIR = Build/target/External
TARGET = $(TARGETDIR)/SDL3
  define BUILDCMDS
	@echo Running build commands
	mkdir -p Build/obj/SDL3
	cmake -S "/home/skyh1ghdev/Programming/DV2591/External"/SDL3 -B Build/obj/SDL3 -DCMAKE_INSTALL_PREFIX=Build/target/External -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_LIBC=ON
	cmake --build Build/obj/SDL3 --config debug --target install
  endef
  define CLEANCMDS
  endef

else ifeq ($(config),release)
TARGETDIR = Build/target/External
TARGET = $(TARGETDIR)/SDL3
  define BUILDCMDS
	@echo Running build commands
	mkdir -p Build/obj/SDL3
	cmake -S "/home/skyh1ghdev/Programming/DV2591/External"/SDL3 -B Build/obj/SDL3 -DCMAKE_INSTALL_PREFIX=Build/target/External -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_LIBC=ON
	cmake --build Build/obj/SDL3 --config release --target install
  endef
  define CLEANCMDS
  endef

else
  $(error "invalid configuration $(config)")
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
